- .cargo/config
- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- LICENSE
- README.md
- cargo-generate.toml
- examples/schema.rs
- src/contract.rs
- src/lib.rs
- tests/integration.rs
Closes #3 
Closes #4
This is a major overhaul, updating to v0.5.0 and new naming schemes, as well as adopting a completely new app logic (simple counter). This should be a minimal example to demonstrate best practices in app development.
> Update cosmwasm 0.5

- README.md
> Use language sh for highlighting shell script blocks

- .gitignore
- meta/README.md
- meta/appveyor.yml
Build time is super slow.
Taking some pages from the circleci config to improve caching and speed up build times.
> Add more caching to appveyor

- Cargo.lock
- Cargo.toml
- Developing.md
- examples/schema.rs
- rustfmt.toml
- schema/count_response.json
- schema/query_msg.json
- schema/state.json
- src/contract.rs
- src/lib.rs
- tests/integration.rs
Closes #15 
Closes #9 
Produce a new template file that produces a solid template for 0.6 apps
> Upgrade to cosmwasm 0.6

- Publishing.md
Closes #20 
Proper commands for the new style
> Update publishing for 0.6 cosmwasm-opt

- Cargo.lock
- Cargo.toml
- schema/state.json
- src/contract.rs
- src/state.rs
- tests/integration.rs
closes #28 
Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>
> dependencies: update the template to 0.7

- .github/workflows/Basic.yml
- README.md
- src/contract.rs
Closes #27 
You can see this in action here: https://github.com/ethanfrey/demo2/actions
(Note: After running generate and before pushing, I ran `cargo check` as I documented in `README.md`)
> Add GitHub workflows

- Cargo.toml
- examples/schema.rs
- meta/test_generate.sh
- src/contract.rs
- tests/integration.rs
This adds a few additional changes to #37. If they are good, we can merge everything together into master.
> Adapt template to 0.8.0-alpha1

- .gitignore
- README.md
> Document 0.8 generation in README

- .circleci/config.yml
- .github/workflows/Basic.yml
- Cargo.toml
- Developing.md
- examples/schema.rs
- meta/test_generate.sh
- schema/state.json
- src/contract.rs
- src/lib.rs
- src/state.rs
- tests/integration.rs
Update to newly tagged v0.8.0 cosmwasm.
> Update to 0.8

- Cargo.toml
- Developing.md
- tests/integration.rs
> Replace cosmwasm-opt with rust-optimizer

- meta/appveyor.yml
There was a build error in #44 due to CI setup
This fixes it, so the CI gives proper results again.
> Fix up appveyor ci script

- .circleci/config.yml
- .github/workflows/Basic.yml
- Cargo.toml
- Developing.md
- README.md
- meta/appveyor.yml
- src/contract.rs
- tests/integration.rs
> Update to 0.10

- README.md
Yeah I put `orkunkl` there... thinking why would I name a project after my name 🤔
> Rename YOUR_NAME_HERE to PROJECT_NAME

- Cargo.toml
- Developing.md
- Publishing.md
- README.md
- src/contract.rs
- src/error.rs
- src/lib.rs
> V0.11 support

- Cargo.toml
- README.md
Depends on https://github.com/CosmWasm/cosmwasm-template/pull/60
After you merge this can you make 0.9, 0.10, 0.11, 0.12, 0.13 protected branches
> Update deps to 0.13

- README.md
> Change rust version to v1.47 in readme

- Cargo.lock
- Cargo.toml
- Developing.md
- src/contract.rs
- src/state.rs
Better to make plus storage visible to newbies.
> Use cw-storage-plus

- .github/workflows/Basic.yml
This PR updates github actions build to use rust 1.51.0
> Update github actions build to rust 1.51.0

- .circleci/config.yml
- .gitpod.yml
- README.md
`cw-gitpod-base` docker image for speeds up gitpod environment launch.
> Setup cw-gitpod-base docker hub CI push

- README.md
- meta/README.md
- meta/appveyor.yml
- meta/test_generate.sh
closes https://github.com/CosmWasm/cw-template/issues/83
> Substitute cosmwasm-template with cw-template

- Cargo.toml
- src/contract.rs
Related request: https://github.com/CosmWasm/cw-template/pull/87#pullrequestreview-751220343
> Bump cosmwasm-std and add set_contract_version

- meta/appveyor.yml
Added docker build and push steps to `appveyor.yml` config for `cw-gitpod-base` image
> Add cw-gitpod-base docker hub push for appveyor CI

- README.md
Documentation change to reflect remote being called `main`.
> fix: master -> main

- .github/workflows/Basic.yml
- Cargo.toml
- Developing.md
- meta/appveyor.yml
- src/helpers.rs
- src/integration_tests.rs
- src/lib.rs
- Use cw-plus 0.12
- Implement helpers and integration_test: good to push this out
> Release 1.0 beta5

- .github/workflows/Basic.yml
This seems to work based on local testing
> Check for schema changes

- src/contract.rs
fix this issue: https://github.com/InterWasm/cw-template/issues/117#issue-1268390101
> fixed mock_dependencies_with_balances bug in contract.rs tests

- Developing.md
> fix rust-optimizer version to latest 0.12.6

- examples/schema.rs
- schema/get_count_response.json
Due to #125, it introduces compile error and mismatching output schema, this PR is the fix.
> Fix CountResponse -> GetCountResponse compile error

- meta/appveyor.yml
> Fix Appveyor CI config

- cargo-generate.toml
Reordering to have the question just before the >true / >false prompt. Also adding a blank line between the explanation and the question for easy visibility
> It's confusing to know what the question actually is

- Cargo.toml
- Developing.md
- meta/appveyor.yml
> Developing md file: bump rust-optimizer version 0.12.11 » 0.14.0

- Cargo.toml
- README.md
also bumped our other packages, removed cosmwasm-storage and the readme reference
> Update cosmwasm to 1.4

- Developing.md
- Importing.md
- README.md
Just a small fix for typos I found while researching this repo
> Fix typos in .md files
